import 'package:equatable/equatable.dart';

/// Aggregated portfolio risk summary generated by the risk engine.
class PortfolioRiskReport extends Equatable {
  /// Creates a [PortfolioRiskReport].
  const PortfolioRiskReport({
    required this.portfolioId,
    required this.generatedAt,
    required this.valueAtRisk95,
    required this.expectedShortfall,
    required this.betaToMarket,
    required this.concentrationScore,
  });

  /// Portfolio identifier.
  final String portfolioId;

  /// Timestamp when this report was generated.
  final DateTime generatedAt;

  /// Value at Risk at the 95% confidence level (as a fraction, e.g. 0.08 = 8%).
  final double valueAtRisk95;

  /// Expected Shortfall (CVaR) — average loss beyond VaR.
  final double expectedShortfall;

  /// Portfolio beta relative to the market benchmark.
  final double betaToMarket;

  /// Herfindahl–Hirschman concentration score [0.0–1.0];
  /// lower is more diversified.
  final double concentrationScore;

  /// Returns `true` when VaR exceeds 10% of portfolio value.
  bool get isHighRisk => valueAtRisk95 > 0.10;

  /// Returns `true` when the portfolio is broadly diversified.
  bool get isDiversified => concentrationScore < 0.30;

  /// Returns `true` when portfolio beta is above 1.2.
  bool get isHighBeta => betaToMarket > 1.20;

  @override
  List<Object?> get props => [
    portfolioId,
    generatedAt,
    valueAtRisk95,
    expectedShortfall,
    betaToMarket,
    concentrationScore,
  ];
}
