name = "crosstide-api"
main = "index.ts"
compatibility_date = "2024-12-01"

[vars]
ENVIRONMENT = "production"
# Bump this whenever you make a backwards-incompatible API change
API_VERSION = "1"

[dev]
port = 8787
local_protocol = "http"
